### PR TITLE
Update deploy.yml

### PR DESCRIPTION
**Pull request by tlienart**
The screenshot below shows that the build is successful (goes all the way to cleanup), what fails is the git checkout. 
Screenshot 2022-03-08 at 09 12 29

there were a few mistakes in the deploy script, this should help and hopefully fix the error post-build.

### CODE REVIEW

**Comment by tlienart** [comment]
I updated the build action to add more defaults so that you don't have to specify fewer things

**Comment by tlienart** [comment]
aaaah wait wait, there's still stuff leftover from development in that action, I need to fix that

**Comment by tlienart** [comment]
alright this should be good now, I had a bit of a fight with GitHub action which handles conditionals in a crappy way but it should be good now.

**Comment by kdheepak** [comment]
Thank you so much for looking into this!

**Pull request merged**
